name: Dev build and publish Java distributions to sonatype snapshot repository and python to PyPi

on:
  push:
    branches-ignore:
      - master
      - version-*
    paths-ignore:
      - README.md

jobs:
  build-job:
    uses: th2-net/.github/.github/workflows/compound-java-dev.yml@main
    with:
      build-target: 'Sonatype'
      runsOn: ubuntu-latest
    secrets:
      sonatypeUsername: ${{ secrets.SONATYPE_NEXUS_USERNAME }}
      sonatypePassword: ${{ secrets.SONATYPE_NEXUS_PASSWORD }}
      sonatypeSigningKey: ${{ secrets.SONATYPE_GPG_ARMORED_KEY }}
      sonatypeSigningPassword: ${{ secrets.SONATYPE_SIGNING_PASSWORD }}
      nvd-api-key: ${{ secrets.NVD_APIKEY }}
  collect-version:
    name: Get version from gradle.properties
    uses: th2-net/.github/.github/workflows/compound-prebuild-java-dev-workflow.yml@main
  build-n-publish:
    name: Dev build and Python distributions to PyPI
    needs: [collect-version]
    uses: th2-net/.github/.github/workflows/compaund-python-grpc-pypi-publication.yml@main
    with:
      custom-version: ${{ needs.collect-version.outputs.versionNumber }}.dev${{ github.run_id }}
    secrets:
      pypi_password: ${{ secrets.PYPI_PASSWORD }}
  scan:
    name: Vulnerabilities scan
    uses: th2-net/.github/.github/workflows/python-scan.yml@main