name: Build and release Java distributions to sonatype and python to PyPi

on:
  workflow_dispatch:

jobs:
  build:
    uses: th2-net/.github/.github/workflows/compound-java.yml@main
    with:
      build-target: 'Sonatype'
      runsOn: ubuntu-latest
      devRelease: false
      createTag: true
    secrets:
      sonatypeUsername: ${{ secrets.SONATYPE_NEXUS_USERNAME }}
      sonatypePassword: ${{ secrets.SONATYPE_NEXUS_PASSWORD }}
      sonatypeSigningKey: ${{ secrets.SONATYPE_GPG_ARMORED_KEY }}
      sonatypeSigningPassword: ${{ secrets.SONATYPE_SIGNING_PASSWORD }}
      nvd-api-key: ${{ secrets.NVD_APIKEY }}
  build-n-publish:
    name: Build and Python distributions to PyPI
    uses: th2-net/.github/.github/workflows/compaund-python-grpc-pypi-publication.yml@main
    secrets:
      pypi_password: ${{ secrets.PYPI_PASSWORD }}
  scan:
    name: Vulnerabilities scan
    uses: th2-net/.github/.github/workflows/python-scan.yml@main